name: Pytest

on: [pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
      - run: |
          pytest $(git ls-files '*.py')
